"""polygan

Revision ID: 62e8addc6080
Revises: ed7c39b40c17
Create Date: 2026-05-10 05:26:11.208809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62e8addc6080'
down_revision: Union[str, Sequence[str], None] = 'ed7c39b40c17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Rooms', sa.Column('polygon', sa.JSON(), nullable=True))
    op.add_column('Rooms', sa.Column('camera_id', sa.Integer(), nullable=True))
    op.drop_column('Rooms', 'capacity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Rooms', sa.Column('capacity', sa.INTEGER(), nullable=True))
    op.drop_column('Rooms', 'camera_id')
    op.drop_column('Rooms', 'polygon')
    # ### end Alembic commands ###
