"""Initial migration for DetectionLogs table

Revision ID: 814c56ca860c
Revises: 
Create Date: 2026-02-16 09:24:39.215086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '814c56ca860c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DetectionLogs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('person', sa.String(length=200), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('detection_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('face_image_path', sa.String(length=512), nullable=True),
    sa.Column('video_path', sa.String(length=512), nullable=True),
    sa.Column('camera_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_detection_time', 'DetectionLogs', ['detection_time'], unique=False)
    op.create_index('idx_person', 'DetectionLogs', ['person'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_person', table_name='DetectionLogs')
    op.drop_index('idx_detection_time', table_name='DetectionLogs')
    op.drop_table('DetectionLogs')
    # ### end Alembic commands ###
