"""add area to log table

Revision ID: 8309582e5107
Revises: 
Create Date: 2026-05-03 09:26:32.123376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8309582e5107'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Personnel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fname', sa.NVARCHAR(length=100), nullable=False),
    sa.Column('lname', sa.NVARCHAR(length=100), nullable=False),
    sa.Column('national_code', sa.String(length=20), nullable=False),
    sa.Column('staff', sa.Boolean(), nullable=True),
    sa.Column('department', sa.NVARCHAR(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Personnel_national_code'), 'Personnel', ['national_code'], unique=False)
    op.create_table('Rooms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_number', sa.String(length=50), nullable=False),
    sa.Column('room_name', sa.NVARCHAR(length=200), nullable=True),
    sa.Column('room_type', sa.NVARCHAR(length=100), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('description', sa.NVARCHAR(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Rooms_room_number'), 'Rooms', ['room_number'], unique=True)
    op.create_table('DetectionLogs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ref_img_id', sa.Integer(), nullable=True),
    sa.Column('person', sa.String(length=200), nullable=False),
    sa.Column('area', sa.String(length=200), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('detection_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('face_image_path', sa.String(length=512), nullable=True),
    sa.Column('video_path', sa.String(length=512), nullable=True),
    sa.Column('camera_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('access_granted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['Rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('PersonnelImages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('image_url', sa.Unicode(length=500), nullable=False),
    sa.Column('personnel_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['personnel_id'], ['Personnel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personnel_room_association',
    sa.Column('personnel_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['personnel_id'], ['Personnel.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['Rooms.id'], ),
    sa.PrimaryKeyConstraint('personnel_id', 'room_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personnel_room_association')
    op.drop_table('PersonnelImages')
    op.drop_table('DetectionLogs')
    op.drop_index(op.f('ix_Rooms_room_number'), table_name='Rooms')
    op.drop_table('Rooms')
    op.drop_index(op.f('ix_Personnel_national_code'), table_name='Personnel')
    op.drop_table('Personnel')
    # ### end Alembic commands ###
