"""Initial migration for DetectionLogs table

Revision ID: 8e24d9d1c679
Revises: 2323ea0e9ca7
Create Date: 2026-02-17 09:58:22.516351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e24d9d1c679'
down_revision: Union[str, Sequence[str], None] = '2323ea0e9ca7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
