"""rooms table

Revision ID: a0e794256fd3
Revises: d80c58165099
Create Date: 2026-04-30 05:28:32.798848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0e794256fd3'
down_revision: Union[str, Sequence[str], None] = 'd80c58165099'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Use batch mode for SQLite compatibility when modifying existing tables
    with op.batch_alter_table('DetectionLogs') as batch_op:
        batch_op.create_foreign_key('fk_detection_logs_rooms', 'Rooms', ['room_id'], ['id'])
    
    # Adding a new column to an existing table also needs batch mode
    with op.batch_alter_table('PersonnelImages') as batch_op:
        batch_op.add_column(sa.Column('is_primary', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('PersonnelImages') as batch_op:
        batch_op.drop_column('is_primary')
    
    with op.batch_alter_table('DetectionLogs') as batch_op:
        batch_op.drop_constraint('fk_detection_logs_rooms', type_='foreignkey')
    # ### end Alembic commands ###