"""national code unique false

Revision ID: af18c4e1d013
Revises: f441cd45b41b
Create Date: 2026-04-11 13:04:03.938615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af18c4e1d013'
down_revision: Union[str, Sequence[str], None] = 'f441cd45b41b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Personnel_national_code'), table_name='Personnel')
    op.create_index(op.f('ix_Personnel_national_code'), 'Personnel', ['national_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Personnel_national_code'), table_name='Personnel')
    op.create_index(op.f('ix_Personnel_national_code'), 'Personnel', ['national_code'], unique=True)
    # ### end Alembic commands ###
