"""add personnel table

Revision ID: bb55927a5659
Revises: 814c56ca860c
Create Date: 2026-02-16 11:46:46.340372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb55927a5659'
down_revision: Union[str, Sequence[str], None] = '814c56ca860c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Personnel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fname', sa.String(length=100), nullable=False),
    sa.Column('lname', sa.String(length=100), nullable=False),
    sa.Column('national_code', sa.String(length=20), nullable=False),
    sa.Column('staff', sa.Boolean(), nullable=True),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_name', 'Personnel', ['fname', 'lname'], unique=False)
    op.create_index('idx_national_code', 'Personnel', ['national_code'], unique=False)
    op.create_index(op.f('ix_Personnel_national_code'), 'Personnel', ['national_code'], unique=True)
    op.add_column('DetectionLogs', sa.Column('personnel_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'DetectionLogs', 'Personnel', ['personnel_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'DetectionLogs', type_='foreignkey')
    op.drop_column('DetectionLogs', 'personnel_id')
    op.drop_index(op.f('ix_Personnel_national_code'), table_name='Personnel')
    op.drop_index('idx_national_code', table_name='Personnel')
    op.drop_index('idx_name', table_name='Personnel')
    op.drop_table('Personnel')
    # ### end Alembic commands ###
