"""add area to log table

Revision ID: d80c58165099
Revises: f2da14ba81d2
Create Date: 2026-04-22 08:33:11.948414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd80c58165099'
down_revision: Union[str, Sequence[str], None] = 'f2da14ba81d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DetectionLogs', sa.Column('area', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('DetectionLogs', 'area')
    # ### end Alembic commands ###
