"""add img ref id to log table

Revision ID: f2da14ba81d2
Revises: 1c58ba422291
Create Date: 2026-04-12 08:57:46.064209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2da14ba81d2'
down_revision: Union[str, Sequence[str], None] = '1c58ba422291'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DetectionLogs', sa.Column('ref_img_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('DetectionLogs', 'ref_img_id')
    # ### end Alembic commands ###
