"""initial_schema

Revision ID: f441cd45b41b
Revises: 
Create Date: 2024-02-23 10:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.mssql import NVARCHAR

# revision identifiers, used by Alembic.
revision = 'f441cd45b41b'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DetectionLogs',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('person', sa.String(length=200), nullable=False),
        sa.Column('confidence', sa.Float(), nullable=True),
        sa.Column('detection_time', sa.DateTime(), server_default=sa.text('(getdate())'), nullable=True),
        sa.Column('face_image_path', sa.String(length=512), nullable=True),
        sa.Column('video_path', sa.String(length=512), nullable=True),
        sa.Column('camera_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('(getdate())'), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('Personnel',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('fname', NVARCHAR(length=100), nullable=False),
        sa.Column('lname', NVARCHAR(length=100), nullable=False),
        sa.Column('national_code', sa.String(length=20), nullable=False),
        sa.Column('staff', sa.Boolean(), nullable=True),
        sa.Column('department', NVARCHAR(length=200), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('(getdate())'), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('national_code')
    )
    op.create_index(op.f('ix_Personnel_national_code'), 'Personnel', ['national_code'], unique=True)
    
    op.create_table('PersonnelImages',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('image_url', sa.Unicode(length=500), nullable=False),
        sa.Column('personnel_id', sa.Integer(), nullable=False),
        sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('(getdate())'), nullable=True),
        sa.ForeignKeyConstraint(['personnel_id'], ['Personnel.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PersonnelImages')
    op.drop_table('Personnel')
    op.drop_table('DetectionLogs')
    # ### end Alembic commands ###